export const DISPLAY_ALERT = "SHOW_ALERT"
export const CLEAR_ALERT = "CLEAR_ALERT"

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"

export const STAFF_REGISTER_USER_BEGIN = "STAFF_REGISTER_USER_BEGIN"
export const STAFF_REGISTER_USER_SUCCESS = "STAFF_REGISTER_USER_SUCCESS"
export const STAFF_REGISTER_USER_ERROR = "STAFF_REGISTER_USER_ERROR"


export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER' 

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CREATE_BOOKING_BEGIN = 'CREATE_BOOKING_BEGIN' 
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS' 
export const CREATE_BOOKING_ERROR = 'CREATE_BOOKING_ERROR' 

export const GET_BOOKINGS_BEGIN = 'GET_BOOKING_BEGIN'
export const GET_BOOKINGS_SUCCESS = 'GET_BOOKING_SUCCESS'

export const GET_PHOTOS_BEGIN = 'GET_PHOTOS_BEGIN'
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS'

export const GET_WEDDING_PHOTOS_BEGIN = 'GET_WEDDING_PHOTOS_BEGIN'
export const GET_WEDDING_PHOTOS_SUCCESS = 'GET_WEDDING_PHOTOS_SUCCESS'


export const GET_BIRTHDAY_PHOTOS_BEGIN = 'GET_BIRTHDAY_PHOTOS_BEGIN'
export const GET_BIRTHDAY_PHOTOS_SUCCESS = 'GET_BIRTHDAY_PHOTOS_SUCCESS'

export const GET_CORPORATE_PHOTOS_BEGIN = 'GET_CORPORATE_PHOTOS_BEGIN'
export const GET_CORPORATE_PHOTOS_SUCCESS = 'GET_CORPORATE_PHOTOS_SUCCESS'

export const GET_GENDER_PHOTOS_BEGIN = 'GET_GENDER_PHOTOS_BEGIN'
export const GET_GENDER_PHOTOS_SUCCESS = 'GET_GENDER_PHOTOS_SUCCESS'

export const GET_BAPTISMAL_PHOTOS_BEGIN = 'GET_BAPTISMAL_PHOTOS_BEGIN'
export const GET_BAPTISMAL_PHOTOS_SUCCESS = 'GET_BAPTISMAL_PHOTOS_SUCCESS'

export const GET_DEBUT_PHOTOS_BEGIN = 'GET_DEBUT_PHOTOS_BEGIN'
export const GET_DEBUT_PHOTOS_SUCCESS = 'GET_DEBUT_PHOTOS_SUCCESS'

export const GET_KIDDIE_PHOTOS_BEGIN = 'GET_KIDDIE_PHOTOS_BEGIN'
export const GET_KIDDIE_PHOTOS_SUCCESS = 'GET_KIDDIE_PHOTOS_SUCCESS'

export const SET_ACCEPT_BOOKING = 'SET_BOOKING_BOOKING'
export const SET_CANCEL_BOOKING = 'SET_CANCEL_BOOKING'

export const ACCEPT_BOOKING_BEGIN = 'ACCEPT_BOOKING_BEGIN' 
export const ACCEPT_BOOKING_SUCCESS = 'ACCEPT_BOOKING_SUCCESS' 
export const ACCEPT_BOOKING_ERROR = 'ACCEPT_BOOKING_ERROR' 

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const CLEAR_FILTERS =  "CLEAR_FILTERS"
export const CHANGE_PAGE = 'CHANGE_PAGE'

export const UPLOAD_PHOTOS_BEGIN = 'UPLOAD_PHOTOS_BEGIN'
export const UPLOAD_PHOTOS_SUCCESS = 'UPLOAD_PHOTOS_SUCCESS'

export const DELETE_UPLOAD_BEGIN = 'DELETE_UPLOAD_BEGIN'
export const DELETE_UPLOAD_SUCCESS = 'DELETE_UPLOAD_SUCCESS'

export const SUBMIT_PHOTOS_BEGIN = 'SUBMIT_PHOTOS_BEGIN'
export const SUBMIT_PHOTOS_SUCCESS = 'SUBMIT_PHOTOS_SUCCESS'

